# Generated by Django 5.0 on 2023-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
