# Generated by Django 5.0 on 2023-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofile_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
