# Generated by Django 5.0 on 2023-12-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
