# Generated by Django 5.0 on 2023-12-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
